name: Deploy Laravel Backend

# Trigger the workflow on push and pull request events on the production branch
on:
    push:
      branches:
        - main
      paths-ignore:
        - 'react/**'
    pull_request:
      branches:
        - main
      paths-ignore:
        - 'react/**' 

# Authenticate to the the server via ssh and run our deployment script 
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        # - name: PHP Setup
        #   uses: shivammathur/setup-php@v2
        #   with:
        #     php-version: '8.2'
  
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        # - name: Node Setup
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: 16
  
        # - name: MySQL Setup
        #   uses: mirromutth/mysql-action@v1.1
        #   with:
        #     mysql database: laravel-test-database
        #     mysql user: laravel_test_user
        #     mysql password: example
  
        # - name: Copy .env
        #   run: cp .env.example .env
        
        # - name: Install Composer Dependencies
        #   run: composer.phar install -q --no-ansi --no-interaction --no-scripts--no-progress --prefer-dist

        # - name: Install node dependencies
        #   run: npm ci
  
        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache
  
        - name: SSH into Server and Deploy
          if: ${{ success() }}
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            password: ${{ secrets.SSH_PRIVATE_PASSWORD }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
                cd ${{ secrets.PROJECT_PATH }}
                git pull origin main
                git clean -f -d
                php artisan migrate --force
                php artisan cache:clear
                php artisan config:cache
