name: Deploy React Frontend

# Trigger the workflow on push and pull request events on the production branch
on:
  push:
    branches:
      - main
    paths:
      - 'react/**'
  pull_request:
    branches:
      - main
    paths:
      - 'react/**'
      
# Authenticate to the the server via ssh and run our deployment script 
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up .env.production file
      run: |
        echo "VITE_API_BASE_URL=${{ secrets.API_URL }}" > react/.env.production

    - name: Install dependencies and build project
      run: |
        cd react
        npm install
        npm run build

    - name: Sync build directory with frontend directory
      uses: easingthemes/ssh-deploy@v5.1.0     
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "react/dist/"
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.SERVER_PORT }}
        REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
        TARGET: ${{ secrets.FRONTEND_PATH }}

