name: Deploy React Frontend

# Trigger the workflow on push and pull request events on the production branch
on:
  push:
    branches:
      - main
    # paths:
    #   - 'domains/api.dabadub.com/react/**'
  pull_request:
    branches:
      - main
    # paths:
    #   - 'domains/api.dabadub.com/react/**'
      
# Authenticate to the the server via ssh and run our deployment script 
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build
      run: |
        cd react
        npm install
        npm run build

    # - name: Sync build directory with frontend directory
    #   run: |
    #     rsync -r -e "ssh -p ${{ secrets.SERVER_PORT }}" "${{ secrets.PROJECT_PATH }}/react/dist/**" ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.FRONTEND_PATH }}


    - name: Sync build directory with frontend directory
      uses: easingthemes/ssh-deploy@v5.1.0     
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "react/dist/"
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.SERVER_PORT }}
        REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
        TARGET: ${{ secrets.FRONTEND_PATH }}

