name: Deploy React Frontend

# Trigger the workflow on push and pull request events on the production branch
on:
  push:
    branches:
      - main
    # paths:
    #   - 'domains/api.dabadub.com/react/**'
  pull_request:
    branches:
      - main
    # paths:
    #   - 'domains/api.dabadub.com/react/**'
      
# Authenticate to the the server via ssh and run our deployment script 
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build
      run: |
        cd react # Cambia esto a la ruta del frontend en tu proyecto
        npm install
        npm run build

    - name: Build React Frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{ secrets.SSH_PRIVATE_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ${{ secrets.FRONTEND_PATH }}
          npm install
          npm run build

    - name: Copy Build Files to target directory
      run: |
        rsync -r -e "ssh -p ${{ secrets.PORT }}" "${{ secrets.PROJECT_PATH }}/react/dist/**" ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.FRONTEND_PATH }}


    # - name: ssh deploy
    #   uses: easingthemes/ssh-deploy@v5.1.0     
    #   with:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     ARGS: "-rltgoDzvO"
    #     SOURCE: "dist/"
    #     REMOTE_HOST: ${{ secrets.SERVER_HOST }}
    #     REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
    #     TARGET: ${{ secrets.FRONTEND_PATH }}

